app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

videos:
    type:     rest
    resource: VideoBundle\Controller\VideoController

coresphere_console:
    resource: .
    type: extra
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc